unit Services.Restaurantes.Favorito.Test;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Services.Restaurantes.Favorito.Utilizado, Domain.Favoritos, SysUtils, DateUtils,
  Repositories;

type
  // Test methods for class TServicesRestaurantesFavoritoUtilizado
  TestTServicesRestaurantesFavoritoUtilizado = class(TTestCase)
  strict private
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestTestarRestauranteUtilizadoSemana;
  end;

implementation

procedure TestTServicesRestaurantesFavoritoUtilizado.SetUp;
begin
end;

procedure TestTServicesRestaurantesFavoritoUtilizado.TearDown;
begin
end;

procedure TestTServicesRestaurantesFavoritoUtilizado.TestTestarRestauranteUtilizadoSemana;
const
  Restaurante1 = 'Restaurante 1';
  Restaurante2 = 'Restaurante 2';
  EMAILTESTE = 'EMAIL TESTE';
  EMAILTESTE2 = 'EMAIL TESTE 2';
var
  ReturnValue: Boolean;
  psRestaurante: string;
  bUtilizado: Boolean;
begin
  TRepositories.New.Favoritos.Add(
    TDomainFavoritos.New(Restaurante1, EMAILTESTE)
    .SetData(IncDay(Now, -1))
  );

  TRepositories.New.Favoritos.Add(
    TDomainFavoritos.New(Restaurante2, EMAILTESTE)
     .SetData(IncDay(Now, -1))
  );

  TRepositories.New.Favoritos.Add(
    TDomainFavoritos.New(Restaurante1, EMAILTESTE)
     .SetData(IncDay(Now))
  );
  TRepositories.New.Favoritos.Add(
    TDomainFavoritos.New(Restaurante1, EMAILTESTE2)
     .SetData(IncDay(Now))
  );

  TRepositories.New.Favoritos.Add(
    TDomainFavoritos.New(Restaurante2, 'EMAIL TESTE 3')
     .SetData(IncDay(Now))
  );

  bUtilizado := TServicesRestaurantesFavoritoUtilizado.TestarRestauranteUtilizadoSemana('Restaurante 1', Now);

  Check(bUtilizado);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTServicesRestaurantesFavoritoUtilizado.Suite);
end.

