unit Services.Favoritos.Existe.Test;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, SysUtils, Services.Favoritos.Existe,
  Domain.Favoritos.Interfaces, Services.Favoritos;

type
  // Test methods for class TServicesFavoritosExiste

  TestTServicesFavoritosExiste = class(TTestCase)
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetExistenteVazio;
    procedure TestGetExistente;
  end;

implementation

procedure TestTServicesFavoritosExiste.SetUp;
begin
end;

procedure TestTServicesFavoritosExiste.TearDown;
begin
end;

procedure TestTServicesFavoritosExiste.TestGetExistenteVazio;
var
  ret: IDomainFavoritosInterfaces;
begin
  ret := TServicesFavoritosExiste.GetExistente(EmptyStr);

  Assert(ret = nil);
end;

procedure TestTServicesFavoritosExiste.TestGetExistente;
const
  TESTE = 'TESTE';
var
  ret: IDomainFavoritosInterfaces;
begin
  TServicesFavoritos.New.Gravar(TESTE, TESTE);
  ret := TServicesFavoritosExiste.GetExistente(TESTE);

  Assert(ret <> nil);
end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTServicesFavoritosExiste.Suite);

end.
